"""empty message

Revision ID: 57483a1920f3
Revises: 03f30f957891
Create Date: 2020-11-08 13:50:44.737063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57483a1920f3'
down_revision = '03f30f957891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
